### PR TITLE
only include valid/invalid/warning report sections in completion email

### PR DESCRIPTION
**Pull request by rw-bsi**
only include valid/invalid/warning report sections (now mirrors the status of the dashboard)

### CODE REVIEW

**Review by aothms — APPROVED** [review]
Looks good to me. The status combination (or appropriate storage in DB) needs to be handled way earlier in the background jobs, but this is not the time to address this.

**Comment by rw-bsi** [comment]
> Looks good to me. The status combination (or appropriate storage in DB) needs to be handled way earlier in the background jobs, but this is not the time to address this.

Agreed - these `combine` methods are popping up everywhere. Perhaps add them in `ifc_validation_models` like https://github.com/buildingSMART/ifc-validation-data-model/blob/1ca6f9725c738510ae2218c4cd32f382d1f9ea95/models.py#L898

**Comment by aothms** [comment]
> Perhaps add them in `ifc_validation_models` like [](https://github.com/buildingSMART/ifc-validation-data-model/blob/1ca6f9725c738510ae2218c4cd32f382d1f9ea95/models.py#L898)

Yes, but even a lot of these distinction, such as between IA and IP are not relevant anymore, so they need a more coordinated rewrite across all modules. I also don't know if all future prerequisite checks (not sure if there are going to be additional ones) are going to be merged into the schema column.

In general I think we have quite some clean up work to do. Not in the last place, the migration to the proper autogenerated rest API. Evandro asked for a list of such tasks some time ago when you couldn't join. Would be good if you can maintain a list.

**Comment by evandroAlfieri** [comment]
@aothms @rw-bsi please capture this clean up tasks in Jira otherwise get lost when we close this pr

**Pull request merged**
